### ISSUE TITLE
Finalizing In-process ANCM. 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#440]
Checklist:

### P0:
- [ ] React to ANCM changes for pInvoke layer https://github.com/aspnet/IISIntegration/issues/430 
- [ ] Incorrect response body on large responses. https://github.com/aspnet/IISIntegration/issues/442

### P1:
- [x] Merging UseNativeIIS and UseIISIntegration https://github.com/aspnet/IISIntegration/issues/429 - Fixed with #443 
- [ ] Have IIS Integration consume ANCM from nuget package #424 
- [ ] Fix Path vs Path Base behavior #427 
- [ ] Check content length #433  
- [ ] Implement Drain #436  
- [ ] Implement Abort #438   

### P2:
- [ ] Performance pass https://github.com/aspnet/IISIntegration/issues/432
- [ ] Logging https://github.com/aspnet/IISIntegration/issues/439
- [ ] Mocking ANCM for testing purposes #431 
- [ ] Api/Naming review (Further in the future)

### P3:
- [ ] Removing duplication for opaque streams https://github.com/aspnet/IISIntegration/issues/426
- [ ] Auth and Windows Auth https://github.com/aspnet/IISIntegration/issues/428
- [ ] Change design of Request and Respnonse Body #435  

### P4:
- [ ] Support running multiple in-process applications (very minor changes here, mostly in ANCM) https://github.com/aspnet/AspNetCoreModule/issues/160

**Comment by jkotalik** [comment]
@muratg based on our meeting I think I arranged these in priority order. 
@davidfowl also requested I make a task called "find bugs".

**Comment by jkotalik** [comment]
Closing in favor of the project checklist ( @Eilon  asked me to a while ago) 😄
