### ISSUE TITLE
publish-iis tracking list

### ISSUE THREAD

**Issue by moozzyk** [aspnet/IISIntegration#55]
- [ ] ~~find a better name (this tool just tweaks the web.config rather than publishing anything)~~
 - [ ] ~~add `--version` switch~~
 - [x] wwwroot can be renamed via the webroot parameter in hosting.json or command line
 - [x] add option to publish for Azure (similar to what [dnu publish](https://github.com/aspnet/dnx/blob/819a6e603b0f43ef1a9da539ecc8ecc29a16bdbc/src/Microsoft.Dnx.Tooling/Publish/PublishProject.cs#L568) did)
 - [x] communicate to users what is happening (currently blocked)
 - [x] sign with a strong name

**Comment by moozzyk** [comment]
It is now completed.
